# Generated by Django 5.0.3 on 2024-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_playlist_description_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
